
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.11.0.0
//   Input filename:  BondResolveAssemblyReferenceResponse.bond
//   Output filename: BondResolveAssemblyReferenceResponse_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.Build.Tasks.ResolveAssemblyReferences.Domain
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.0")]
    public partial class ResolveAssemblyReferenceResponse
    {
        [global::Bond.Id(0)]
        public int CopyLocalFilesCount { get; set; }

        [global::Bond.Id(1)]
        public string DependsOnNETStandard { get; set; }

        [global::Bond.Id(2)]
        public string DependsOnSystemRuntime { get; set; }

        [global::Bond.Id(3)]
        public int FilesWrittenCount { get; set; }

        [global::Bond.Id(4)]
        public int RelatedFilesCount { get; set; }

        [global::Bond.Id(5)]
        public int ResolvedDependencyFilesCount { get; set; }

        [global::Bond.Id(6)]
        public int ResolvedFilesCount { get; set; }

        [global::Bond.Id(7)]
        public int SatelliteFilesCount { get; set; }

        [global::Bond.Id(8)]
        public int ScatterFilesCount { get; set; }

        [global::Bond.Id(9)]
        public int SerializationAssemblyFilesCount { get; set; }

        [global::Bond.Id(10)]
        public int SuggestedRedirectsCount { get; set; }

        [global::Bond.Id(11)]
        public List<ReadOnlyTaskItem> TaskItems { get; set; }

        public ResolveAssemblyReferenceResponse()
            : this("Microsoft.Build.Tasks.ResolveAssemblyReferences.BondTypes.BondResolveAssemblyReferenceResponse", "BondResolveAssemblyReferenceResponse")
        { }

        protected ResolveAssemblyReferenceResponse(string fullName, string name)
        {
            DependsOnNETStandard = "";
            DependsOnSystemRuntime = "";
            TaskItems = new List<ReadOnlyTaskItem>();
        }
    }
} // Microsoft.Build.Tasks.ResolveAssemblyReferences.BondTypes
